dist: xenial

addons:
  snaps:
  - hugo

script:
  - hugo version
  - bash ./deploy.sh

branches:
  only:
  - master

env:
  global:
  - ENCRYPTION_LABEL: "bad4e5f1f354"
  - COMMIT_AUTHOR_EMAIL: "wenzhixin2010@gmail.com"
